- hosts: localhost
  vars:
    - node_version: 8
    - is_ci: ansible_env.TRAVIS_JOB_ID is defined
    - isnt_ci: ansible_env.TRAVIS_JOB_ID is not defined
    - is_osx: ansible_os_family == 'Darwin'
    - is_ubuntu: ansible_distribution == 'Ubuntu' or ansible_distribution == '\"elementary\"'
    - dist_release: "{{ 'xenial' if is_ubuntu }}"

  tasks:
    # essentials:
    - include: tasks/apt.yml
    - include: tasks/homebrew.yml
    - include: tasks/core.yml
    - include: tasks/fonts.yml
    - include: tasks/dotfiles.yml
    - include: tasks/shortcuts.yml

    # editors, IDEs, terminals, etc
    - include: tasks/terminal.yml
    - include: tasks/visual-studio-code.yml

    # browsers
    - include: tasks/chrome.yml

    # languages
    # - include: tasks/golang.yml
    # - include: tasks/java.yml
    - include: tasks/node.yml
    - include: tasks/python.yml
    # - include: tasks/ruby.yml

    # tools
    - include: tasks/awscli.yml
    # - include: tasks/docker.yml

    # chat
    - include: tasks/slack.yml

    # media
    - include: tasks/spotify.yml
    # - include: tasks/vlc.yml
