- name: Add Docker keys
  apt_key: url=https://apt.dockerproject.org/gpg
  when: is_ubuntu
- name: Add Docker repository
  apt_repository: 
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ dist_release }} stable"
    state: present
  when: is_ubuntu
- name: Install Docker
  package: name=docker-ce allow_unauthenticated=yes
  when: is_ubuntu

- name: Install Docker for Mac
  homebrew_cask: name=docker
  when: is_osx
