- name: Configure Pantheon Button Layout
  command: gsettings set {{ item }}
  with_items:
  - org.pantheon.desktop.gala.appearance button-layout "'close,minimize,maximize'"
  - org.gnome.desktop.wm.preferences button-layout "'close,minimize,maximize'"

- name: Configure Pantheon Terminal
  command: gsettings set org.pantheon.terminal.settings {{ item }}
  with_items:
  - font 'Cousine for Powerline 10'
  - background '#00002B2B3636'
  - foreground '#838394949696'
  - cursor-shape I-Beam
  - cursor-color '#838394949696'
  - palette '#070736364242:#DCDC32322F2F:#858599990000:#B5B589890000:#26268B8BD2D2:#D3D336368282:#2A2AA1A19898:#EEEEE8E8D5D5:#00002B2B3636:#CBCB4B4B1616:#858599990000:#65657B7B8383:#26268B8BD2D2:#6C6C7171C4C4:#9393A1A1A1A1:#FDFDF6F6E3E3'
  - follow-last-tab true