- name: Check if Visual Studio Code is installed
  command: dpkg-query -W code
  register: check_vscode
  failed_when: false
  changed_when: false
  when: is_ubuntu

- name: Download and Install Visual Studio Code (x86)
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760680
  when:
    - check_vscode.rc == 1
    - ansible_userspace_architecture == 'x86'
    - is_ubuntu

- name: Download and Install Visual Studio Code (x64)
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868
  when:
    - check_vscode.rc == 1
    - ansible_userspace_architecture == 'x86_64'
    - is_ubuntu

- name: Install VisualStudio Code (macOS)
  homebrew_cask: name=visual-studio-code
  when: is_osx
