# - name: Add VisualStudio Code apt keys
#   apt_key: url=https://packages.microsoft.com/keys/microsoft.asc
#   when: is_ubuntu
# - name: Add VisualStudio Code repository
#   apt_repository: repo='deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
#   when: is_ubuntu

- name: Check if Visual Studio Code is installed
  command: dpkg-query -W code
  register: check_vscode
  failed_when: false
  changed_when: false
  when: is_ubuntu

- name: Download Visual Studio Code
  get_url:
    url: "https://az764295.vo.msecnd.net/stable/7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba/code_1.19.3-1516876437_amd64.deb"
    dest: "/tmp/vscode.deb"
  when:
    - check_vscode.rc == 1
    - is_ubuntu

- name: Install Visual Studio Code
  command: gdebi --non-interactive /tmp/vscode.deb
  when:
    - check_vscode.rc == 1
    - is_ubuntu

- name: Install VisualStudio Code
  homebrew_cask: name=visual-studio-code
  when: is_osx
